logging:
  level:
    root: INFO
    za.co.vodacom.repoprofile: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: repo-profile
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Added Feign Timeout Configuration
  cloud:
    openfeign:
      client:
        config:
          github:
            connectTimeout: 2000
            readTimeout: 2000
            loggerLevel: full

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

application:
  github:
    url: https://api.github.com/
    feignClientName: github